name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # Adjust this to your main branch
  pull_request:
    branches:
      - main  # Adjust this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build and run Jekyll
      run: |
        docker run --rm -v $(pwd):/srv/jekyll -e JEKYLL_UID=$(id -u) -e JEKYLL_GID=$(id -g) jekyll/builder:3.8 bash -c "gem update --system && bundle install && jekyll build"
    
    - name: Deploy to GitHub Pages
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
